import {StyleSheet, Dimensions} from 'react-native';
import {color} from 'react-native-reanimated';
import {Colors} from '../../../../constants/Colors';
const {width} = Dimensions.get('screen');
export default StyleSheet.create({
  mainView: {
    flex: 1,
    backgroundColor: '#F5F5F5',
    //alignItems: "center",
  },
  view1: {
    height: '10%',
    width: '100%',
    backgroundColor: Colors.white,
    alignItems: 'center',
    justifyContent: 'space-between',
    // borderBottomLeftRadius: 20,
    // borderBottomRightRadius: 20,
    flexDirection: 'row',
  },
  view12: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    height: 300,
  },
  backIcon: {
    height: 15,
    width: 25,
    marginHorizontal: 15,
  },
  backIcon1: {
    height: 15,
    width: 25,
    marginHorizontal: 15,
  },
  text1: {
    fontSize: 30,
    fontWeight: '600',
    color: Colors.black,
    // marginTop:25,
  },
  text2: {
    fontSize: 12,
    fontWeight: '400',
    color: Colors.switchergray,
    marginTop: 17,
    marginHorizontal: 20,
  },
  text3: {
    fontSize: 18,
    fontWeight: '700',
    color: Colors.dark,
    marginVertical: 10,
    marginHorizontal: 10,
  },
  text4: {
    fontSize: 16,
    fontWeight: '500',
    color: Colors.dark,
  },
  text5: {
    fontSize: 14,
    fontWeight: '400',
    color: Colors.switchergray,
  },
  text6: {
    fontSize: 20,
    fontWeight: 'bold',
    color: Colors.dark,
    marginVertical: 16,
    marginHorizontal: 25,
  },
  //
  header: {
    paddingVertical: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
  },
  profileImage: {
    height: 50,
    width: 50,
    borderRadius: 25,
  },
  searchInputContainer: {
    height: 50,
    backgroundColor: Colors.light,
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    borderRadius: 12,
    marginBottom: 10,
  },
  sortBtn: {
    backgroundColor: Colors.dark,
    height: 50,
    width: 50,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 10,
  },

  optionsCard: {
    height: 210,
    width: width / 2 - 30,
    elevation: 15,
    alignItems: 'center',
    backgroundColor: Colors.white,
    borderRadius: 20,
    paddingTop: 10,
    paddingHorizontal: 10,
  },
  optionsCardImage: {
    height: 140,
    borderRadius: 10,
    width: '100%',
  },
  optionListsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 20,
    paddingHorizontal: 20,
  },
  categoryListText: {
    fontSize: 16,
    fontWeight: 'bold',
    paddingBottom: 5,
    color: Colors.grey,
  },
  activeCategoryListText: {
    color: Colors.dark,
    borderBottomWidth: 1,
    paddingBottom: 5,
  },
  categoryListContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 40,
    paddingHorizontal: 40,
  },
  card: {
    // height: 270,
    backgroundColor: Colors.white,
    elevation: 10,
    width: width - 40,
    marginRight: 20,
    padding: 15,
    borderRadius: 20,
  },
  cardImage: {
    width: '100%',
    height: 150,
    borderRadius: 15,
  },
  facility: {flexDirection: 'row', marginRight: 15},
  facilityText: {marginLeft: 5, color: Colors.grey},
  popupContainer: {
    width: '100%',
    height: '100%',
    position: 'absolute',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    zIndex: 9999,
  },
  slide: {
    alignItems: 'center',
    justifyContent: 'center',
  },
});
